p=float(input("Enter Principal Amount :"))
r=float(input("Enter Rate :"))
t=float(input("Enter Time :"))
si=float(p*r*t/100)
print("Simple Interest =",si)
print("Principal Amount is :",p)
print("Total Amount :",p+si)